### ISSUE TITLE
to-do list for areum v0.0.1

### ISSUE THREAD

**Issue by jdeokkim** [jdeokkim/areum#3]
# v0.0.1

## implement features for each condition flag
- [x] `SR_FLAG_CARRY`
- [x] `SR_FLAG_PARITY`
- [x] `SR_FLAG_AUX_CARRY`
- [x] `SR_FLAG_ZERO`
- [x] `SR_FLAG_SIGN`

### data transfer group
- [x] `MOV r(X), r(Y)`
- [x] `MOV r(X), mem`
- [x] `MOV mem, r(X)`
- [x] `MVI r(X), data(8)`
- [x] `MVI mem, data(8)`
- [x] `LXI rp(X, Y), data(16)`
- [x] `LDA addr`
- [x] `STA addr`
- [x] `LHLD addr`
- [x] `SHLD addr`
- [x] `LDAX rp(X, Y)`
- [x] `STAX rp(X, Y)`
- [x] `XCHG`

### arithmetic group
- [x] `ADD r(X)`
- [x] `ADD mem`
- [x] `ADI data(8)`
- [x] `ADC r(X)`
- [x] `ADC mem`
- [x] `ACI data(8)`
- [x] `SUB r(X)`
- [x] `SUB mem`
- [x] `SUI data(8)`
- [x] `SBB r(X)`
- [x] `SBB mem`
- [x] `SBI data(8)`
- [x] `INR r(X)`
- [x] `INR mem`
- [x] `DCR r(X)`
- [x] `DCR mem`
- [x] `INX rp(X, Y)`
- [x] `DCX rp(X, Y)`
- [x] `DAD rp(X, Y)`
- [x] `DAA`

### logical group
- [x] `ANA r(X)`
- [x] `ANA mem`
- [x] `ANI data(8)`
- [x] `XRA r(X)`
- [x] `XRA mem`
- [x] `XRI data(8)`
- [x] `ORA r(X)`
- [x] `ORA mem`
- [x] `ORI data(8)`
- [x] `CMP r(X)`
- [x] `CMP mem`
- [x] `CPI data(8)`
- [x] `RLC`
- [x] `RRC`
- [x] `RAL`
- [x] `RAR`
- [x] `CMA`
- [x] `CMC`
- [x] `STC`

### branch group
- [x] `JMP addr`
- [x] `J(CCC) addr`
- [x] `CALL addr`
- [x] `C(CCC) addr`
- [x] `RET`
- [x] `R(CCC) addr`
- [x] `RST n`
- [x] `PCHL`

### stack, i/o and machine control group
- [x] `PUSH rp(X, Y)`
- [x] `PUSH psw`
- [x] `POP rp(X, Y)`
- [x] `POP psw`
- [x] `XTHL`
- [x] `SPHL`
- [x] `IN data(8)`
- [x] `OUT data(8)`
- [x] `EI`
- [x] `DI`
- [x] `HLT`
- [x] `NOP`
